from .flex_lora_slider import NODE_CLASS_MAPPINGS as FLEX_LORA_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLEX_LORA_NAME_MAPPINGS
from .flex_xy_grid import NODE_CLASS_MAPPINGS as XY_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as XY_NAME_MAPPINGS
from .flex_image_compare import NODE_CLASS_MAPPINGS as CMP_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CMP_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **FLEX_LORA_CLASS_MAPPINGS,
    **XY_CLASS_MAPPINGS,
    **CMP_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FLEX_LORA_NAME_MAPPINGS,
    **XY_NAME_MAPPINGS,
    **CMP_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]